# 7. Numpy

### (1) Intro, Vectorization

In [3]:
import numpy as np
x = np.random.uniform(0, 1, size = 1000000)
x.mean()

0.50002566886775079

In [7]:
np.zeros(3, dtype = int)

array([0, 0, 0])

In [10]:
z = np.zeros(10)    # z is a flat array
z.shape

(10,)

In [11]:
z.shape = (10,1)    # change the shape, now it's a column vector
z

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [14]:
z = np.zeros(4)
z.shape = (2,2)
z

array([[ 0.,  0.],
       [ 0.,  0.]])

In [19]:
# 单位矩阵
z = np.identity(2)
z

array([[ 1.,  0.],
       [ 0.,  1.]])

In [20]:
# 从2到4， 均匀间隔， 五个数
z = np.linspace(2,4,5)
z

array([ 2. ,  2.5,  3. ,  3.5,  4. ])

### (2) Indexing

In [ ]:
z[0:2]

In [24]:
z[-2]

3.5

In [27]:
z = np.array([[1, 2], [3, 4]])
z[0, 1]

2

In [29]:
z[0, :]

array([1, 2])

In [30]:
# NumPy arrays of integers can also be used to extract elements
z = np.linspace(2, 4, 5)
indices = np.array((0, 2, 3))    # 提出第1, 3, 4个数
z[indices]

array([ 2. ,  3. ,  3.5])

In [31]:
# an array of dtype bool can be used to extract elements
d = np.array([0, 1, 1, 0, 0], dtype=bool)
z[d]

array([ 2.5,  3. ])

In [33]:
z = np.array([[1, 2], [3, 4]])
z[:, :] = 10
z

array([[10, 10],
       [10, 10]])

### (3) Array Methods

Methods: sort, sum, mean, max, argmax, cumsum, cumprod, var, std, shape, T, ...

If z is a nondecreasing array, then z.searchsorted(a) returns the index of the first element of z that is >= a

In [36]:
z = np.linspace(2, 4, 5)
z.searchsorted(2.2)

1

### (4) Operations

$+  -  *\    /  **  @$

### (5) Mutability

In [38]:
# b is just another reference to the array
# we pass around only pointers to data, rather than making copies
a = np.random.randn(3)
a

array([ 0.31120123, -0.31005769,  0.48986685])

In [39]:
b = a
b[0] = 0.0
a

array([ 0.        , -0.31005769,  0.48986685])

In [46]:
# Making copy
a = np.random.randn(3)
a

array([-2.36209034,  0.05659602,  2.96946258])

In [47]:
b = np.empty_like(a)    # empty array with the same shape as a
np.copyto(b, a)
b    # b is called a "deep copy"

array([-2.36209034,  0.05659602,  2.96946258])

### (6) Additional Functionality

#### (6.1) Vectorized Functions

In Numpy-speak, also called _ufuncs_.

In [51]:
z = np.array([1, 2, 3])
np.sin(z)

array([ 0.84147098,  0.90929743,  0.14112001])

Here's a way to vectorize a user defined function:

In [50]:
def f(x):
    return 1 if x > 0 else 0
f = np.vectorize(f)
x = np.random.randn(4)
f(x)

array([1, 1, 0, 1])

#### (6.2) Comparisons

In [57]:
z = np.array((2,3))
y = np.array([2,3])
z == y

array([ True,  True], dtype=bool)

In [59]:
z > 2

array([False,  True], dtype=bool)

In [63]:
b = z > 2
z[b]
# which is equivalent to
z[z > 2]

array([3])

#### (6.3) Subpackages

np.random, np.linalg

### (7) Exercises
#### Q1. numpy polynomial